### PR TITLE
Patch/format numbers

### LINKED ISSUE #9: Could you add format number option
I will very much like have to have an option that formats phone number, thanks

### PR DESCRIPTION
**Pull request by edwinnyawoli**
Add support for formatting numbers into the various phone number formats: 

- **E164**
- **INTERNATIONAL**
- **NATIONAL**
- **RFC3966**

Closes #9

### CODE REVIEW

**Review by mattdarwin — APPROVED** [review]
lgtm, let's get this merged and released

**Comment by emostar** [comment]
@edwinnyawoli can you add an example of using this to the app in the example folder please?

**Comment by edwinnyawoli** [comment]
> @edwinnyawoli can you add an example of using this to the app in the example folder please?

Sure

**Comment by shahmharsh** [comment]
Any ETA on when this will be merged and released?

**Comment by SimonHausdorf** [comment]
any update?

**Pull request merged**
