### PR TITLE
migrated to null safety #26

### PR DESCRIPTION
**Pull request by pr-1**
Hi @emostar I have migrated this to null safety using the dart tool. Please have a look and see if it needs any changes ?

### CODE REVIEW

**Comment by bhavin-concetto** [comment]
@pr-1 you need to update dart version too as I have tried using your PR. I have created new (PR#1)[https://github.com/pr-1/flutter-libphonenumber/pull/1]. Please accept it.

**Comment by pr-1** [comment]
Thanks @bhavin-concetto

**Comment by bhavin-concetto** [comment]
@emostar can you merge this PR?

**Comment by cedvdb** [comment]
it might be useful to add more maintainers to the project too

**Comment by emostar** [comment]
@pr-1 Thank you very much for your contribution!

@cedvdb I'm more than willing to add more maintainers, just need someone to say they will.

**Comment by pr-1** [comment]
You can add me if you want @emostar and csn you release the package now to pub sk that i can start working on updating other packages that depend on this one.

**Comment by emostar** [comment]
@pr-1 Alright, I'll add you.  I just published it to pub as 2.0.0

**Pull request merged**
